#!/usr/bin/env bash

echo "Setting up dotfiles in $(pwd)"

# Store env if provided
if [ "$1" == "home" ] || [ "$1" == "work" ] || [ "$1" == "none" ]; then
  echo "$1" >| ".dotfiles-env"
fi

# Suppress "Last login" message
touch ~/.hushlogin

# Add symlinks
ln -sf $(pwd)/zsh/zshrc ~/.zshrc
ln -sf $(pwd)/git/gitconfig ~/.gitconfig
ln -sf $(pwd)/git/gitignore_global ~/.gitignore_global

mkdir -p ~/.config
ln -sf $(pwd)/starship/config.toml ~/.config/starship.toml

# Setup iTerm2
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.dotfiles/iterm"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Run the update script to install homebrew deps
./update

# Setup vscode
# NOTE: needs to run after brew
# TODO: this should be handled by vscode settings sync now?
#ln -sf $(pwd)/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
#ln -sf $(pwd)/vscode/snippets ~/Library/Application\ Support/Code/User/

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Switch to using brew-installed zsh as default shell
# NOTE: this needs to be run after the update script
if ! fgrep -q "${BREW_PREFIX}/bin/zsh" /etc/shells; then
  echo "${BREW_PREFIX}/bin/zsh" | sudo tee -a /etc/shells;
  chsh -s "${BREW_PREFIX}/bin/zsh";
fi;
