#!/usr/bin/env bash

echo "Setting up dotfiles in $(pwd)"

# Store env if provided
if [ "$1" == "home" ] || [ "$1" == "work" ] || [ "$1" == "none" ]; then
    echo "$1" >| ".dotfiles-env"
fi

# Suppress "Last login" message
touch ~/.hushlogin

# Add symlinks
ln -sf $(pwd)/zsh/zshrc ~/.zshrc
ln -sf $(pwd)/git/gitconfig ~/.gitconfig
ln -sf $(pwd)/git/gitignore_global ~/.gitignore_global
ln -sf $(pwd)/starship/config.toml ~/.config/starship.toml

# Setup iTerm2
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.dotfiles/iterm"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Run the update script to install homebrew deps
./update

# Swap to zsh
# NOTE: this needs to be run after the update script
if [ "$SHELL" != "$(which zsh)" ]; then
  chsh -s $(which zsh)
fi