# Prompt format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$cmd_duration\
$line_break\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""

# Hide the stashed status
[git_status]
stashed = ""