##########
# COLORS #
##########

autoload colors; colors
export CLICOLOR=1

##########
# SETOPT #
##########

setopt PROMPT_SUBST

###########
# EXPORTS #
###########

# Move /usr/local/bin before /usr/bin for homebrew
PATH="$HOME/.jenv/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="$HOME/.dotfiles/bin:$PATH"
export -U PATH

# Enable color in grep
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;37'

export EDITOR='code'
export DISABLE_AUTO_TITLE='true'

# Homebrew cask options
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Ruby setup :(
if type "rbenv" > /dev/null; then
  eval "$(rbenv init -)"
fi

# jenv setup
if type "jenv" > /dev/null; then
  eval "$(jenv init -)"
fi

# nodenv setup
if type "nodenv" > /dev/null; then
  eval "$(nodenv init -)"
fi

# SBT options
export SBT_OPTS="-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xss2M -Duser.timezone=GMT"

# Google App Engine (brew install app-engine-java)
export APPENGINE_SDK_HOME=/usr/local/opt/app-engine-java/libexec

##########
# PROMPT #
##########

autoload -U promptinit; promptinit
prompt pure

# Disable pure prompt's default title behaviour
prompt_pure_set_title() {}

##############
# COMPLETION #
##############

# Enable git completion?
autoload -U compinit && compinit

###########
# ALIASES #
###########

# Colorize output, add file type indicator, and put sizes in human readable format
alias ls='ls -GFha'

# Same as above, but in long listing format
alias ll='ls -GFhla'

# Directory shortcuts
alias dev='cd ~/dev/code'
alias dot='cd ~/.dotfiles'

# Print path
alias path='print -l $path'

# Capsule specific
alias capsule='cd ~/dev/code/capsule'
alias ae='ant explode'
alias au='ant unexplode clean explode'
alias ar='cd ember && yarn install --frozen-lockfile && cd .. && yarn install --frozen-lockfile && ant refresh'
alias j='jboss-eap'
alias t='yarn run ember exam --split=8 --parallel -r=tap'
alias ets='yarn run ember server --environment=test --port=4201'
alias kill-jboss='pkill -9 -f jboss'

#############
# FUNCTIONS #
#############

function g {
  if [[ $# > 0 ]]; then
    git $@
  else
    git status --short --branch
  fi
}

function gsd {
  if [ -n "$1" ]; then
    git stash show -p stash@{"$1"}
  else
    git stash show -p stash@{0}
  fi
}

function open-files {
  lsof | awk '{ print "pid=" $2 ", name=" $1; }' | sort -rn | uniq -c | sort -rn | head -20
}

# Start an HTTP server from a directory, optionally specifying the port
function server() {
  local port="${1:-8000}"
  open "http://localhost:${port}/" && python -m SimpleHTTPServer "$port"
}

function port() {
  lsof -n -i:"$1" | grep LISTEN
}

function mkv2mp4 {
  ffmpeg -i "$1" -codec copy "${1%.*}.mp4"
}

###########
# HISTORY #
###########

HISTSIZE=3000
SAVEHIST=3000
HISTFILE=~/.zsh_history

#########
# HOOKS #
#########

function precmd() {
  # Set the window title to full/directory/path
  echo -ne "\e]2;$PWD\a"

  # Set the tab title to parentdir/currentdir
  echo -ne "\e]1;$PWD:h:t/$PWD:t\a"
}

#############
# ZSH SETUP #
#############

# Highlighting
source `brew --prefix`/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# As per `brew info zsh-completions`
fpath=(`brew --prefix`/share/zsh-completions $fpath)

# As per `brew info zsh-history-substring-search`
source `brew --prefix`/share/zsh-history-substring-search/zsh-history-substring-search.zsh

# Configure zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=green,fg=black,bold'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='bg=red,fg=black,bold'
HISTORY_SUBSTRING_SEARCH_GLOBBING_FLAGS='i'
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=true
